fisrtNumber = int(input("1stNumber : "))
secondNumber = int(input("2ndNumber : "))
plus = fisrtNumber + secondNumber
minus = fisrtNumber - secondNumber
multiply = fisrtNumber * secondNumber
divide = fisrtNumber / secondNumber
print(fisrtNumber,"+",secondNumber,"=",plus)
print(fisrtNumber,"-",secondNumber,"=",minus)
print(fisrtNumber,"*",secondNumber,"=",multiply)
print(fisrtNumber,"/",secondNumber,"=",divide)